[api]
base_url = "https://stream.wikimedia.org/"

# https://stream.wikimedia.org/?doc#/streams/get_v2_stream_recentchange
[topics.recentchange]
path = "/v2/stream/recentchange"
primary_key = ["id"]

[topics.recentchange.schema]
title = "string"
"$schema" = "string"
type = "string"
bot = "bool_"
comment = "string"
id = "int8"
length = "int8"
log_action = "string"
log_id = "int8"
log_params = "json_"
log_type = "string"
meta = "json_"
minor = "bool_"
namespace = "int8"
parsedcomment = "string"
revision = "json_"
server_name = "string"
server_script_path = "string"
server_url = "string"
timestamp = "int8"
user = "string"
wiki = "string"
