default:
  target: app
  outputs:
    app:
      type: duckdb
      path: "ducklake:sqlite:run/data/warehouse/warehouse.sqlite"
      extensions:
        - ducklake
        - sqlite
      options:
        data_path: "run/data/warehouse/data_files"
